export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESSES = 'PRODUCT_LIST_SUCCESSES'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'


export const PRODUCT_REQUEST = 'PRODUCT_REQUEST'
export const PRODUCT_SUCCESSES = 'PRODUCT_SUCCESSES'
export const PRODUCT_FAIL = 'PRODUCT_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESSES = 'PRODUCT_DELETE_SUCCESSES'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'